_wandb:
    value:
        cli_version: 0.23.1
        e:
            trqdakfvub5shmfrw0o9jabbmfotkupf:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 48
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "51539607552"
                    swapTotalBytes: "1073741824"
                codePath: grpo/main.py
                codePathLocal: main.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "494384795648"
                        used: "162586435584"
                email: dirtem1998@gmail.com
                executable: /Users/ozgurcelik/miniconda3/envs/rlvenv/bin/python
                git:
                    commit: 94da487a6f14729b11e1c921de02593a7cbef552
                    remote: https://github.com/ozgurcelik/myrl.git
                host: Ozgurs-MacBook-Pro.local
                memory:
                    total: "51539607552"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/ozgurcelik/Desktop/rl/myrl/grpo/main.py
                python: CPython 3.12.12
                root: /Users/ozgurcelik/Desktop/rl/myrl/grpo
                startedAt: "2026-01-17T15:50:20.834828Z"
                writerId: trqdakfvub5shmfrw0o9jabbmfotkupf
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
            "2":
                - 1
                - 11
                - 49
                - 51
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.12
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": darwin-arm64
batch_per_epoch:
    value: 1
batch_size:
    value: 4
device:
    value: mps
dtype:
    value: torch.float32
epsilon:
    value: 0.2
learning_rate:
    value: 5e-06
max_new_tokens:
    value: 256
model_id:
    value: Qwen/Qwen2.5-0.5B-Instruct
num_epochs:
    value: 50
num_return_sequences:
    value: 4
temperature:
    value: 0.6
test_freq:
    value: 5
update_freq:
    value: 2
